name = "LFUDACache"
uuid = "4ae1174a-2808-43b3-975e-65e36c59b120"
authors = ["Egor Shmorgun <egor.shmorgun@opensesame.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
