name = "LFUDACache"
uuid = "4ae1174a-2808-43b3-975e-65e36c59b120"
authors = ["Egor Shmorgun <egor.shmorgun@opensesame.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
julia = "1"
DataStructures = "0.18"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"

[targets]
test = ["Test", "BenchmarkTools", "Dates", "LRUCache"]
